"""Initial migration

Revision ID: 356779628451
Revises: 
Create Date: 2024-11-30 19:23:53.049447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "356779628451"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventaire",
        sa.Column("id_compte", sa.Integer(), nullable=False),
        sa.Column("id_objet", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_compte"],
            ["compte.id_compte"],
        ),
        sa.ForeignKeyConstraint(
            ["id_objet"],
            ["objet.id_objet"],
        ),
        sa.PrimaryKeyConstraint("id_compte", "id_objet"),
        sa.UniqueConstraint("id_compte", "id_objet", name="uix_id_compte_objet"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventaire")
    # ### end Alembic commands ###
