"""ajouter race tablee

Revision ID: ad56fec4a714
Revises: 
Create Date: 2024-12-18 12:46:30.785251

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad56fec4a714'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race',
    sa.Column('id_race', sa.Integer(), nullable=False),
    sa.Column('nom_race', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('magic', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('carisma', sa.Integer(), nullable=False),
    sa.Column('chance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_race')
    )
    op.create_unique_constraint('uix_id_compte_objettt', 'inventaire', ['id_compte', 'id_objet'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_id_compte_objettt', 'inventaire', type_='unique')
    op.drop_table('race')
    # ### end Alembic commands ###
