"""GLOBAL

Revision ID: c40857d02497
Revises: 
Create Date: 2024-12-16 19:19:17.001878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c40857d02497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('nom_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('compte',
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('addresse', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_compte')
    )
    op.create_table('objet',
    sa.Column('id_objet', sa.Integer(), nullable=False),
    sa.Column('nom_objet', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id_category_objet', sa.Integer(), nullable=False),
    sa.Column('description_objet', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('image_objet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['id_category_objet'], ['category.id_category'], ),
    sa.PrimaryKeyConstraint('id_objet')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('user_login', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_created_at', sa.DateTime(), nullable=False),
    sa.Column('user_login_date', sa.DateTime(), nullable=False),
    sa.Column('user_role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('compte_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['compte.id_compte'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('compte_id')
    )
    op.create_table('inventaire',
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('id_objet', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_compte'], ['compte.id_compte'], ),
    sa.ForeignKeyConstraint(['id_objet'], ['objet.id_objet'], ),
    sa.PrimaryKeyConstraint('id_compte', 'id_objet'),
    sa.UniqueConstraint('id_compte', 'id_objet', name='uix_id_compte_objet')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventaire')
    op.drop_table('user')
    op.drop_table('objet')
    op.drop_table('compte')
    op.drop_table('category')
    # ### end Alembic commands ###
